image: rust:slim

variables:
  RUSTFLAGS: "-Dwarnings"

stages:
  - build
  - static-analysis
  - test
  - docs

.install_dependencies:
  before_script:
    - apt update
    - apt install curl -y
    - apt install libssl-dev pkg-config -y
    - apt install -y protobuf-compiler libprotobuf-dev

build:
  stage: build
  extends: .install_dependencies
  script:
    - cargo build

format-check:
  stage: static-analysis
  needs: ["build"]
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy-check:
  stage: static-analysis
  needs: ["build"]
  extends: .install_dependencies
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

tests:
  stage: test
  needs: ["format-check", "clippy-check"]
  extends: .install_dependencies
  script:
    - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - cargo nextest run --profile ci -E 'not (test(/integration*/))'
    - mv target/nextest/ci/junit.xml .
  artifacts:
    when: always
    reports:
      junit: junit.xml
  allow_failure: true

docs:
  stage: docs
  needs: ["tests"]
  extends: .install_dependencies
  script:
    - cargo doc
    - mv target/doc public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
