image: rust:slim

variables:
  RUSTFLAGS: "-Dwarnings"

stages:
  - build
  - lint
  - test

build:
  stage: build
  script:
    - cargo build

format-check:
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy-check:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

tests:
  stage: test
  script:
    - cargo test