image: rust:latest

stages:
  - build
  - format
  - test

check-compilation:
  stage: build
  script:
    - cargo build

check-formatting:
  stage: format
  script:
    - rustup component add rustfmt
    - cargo fmt --check

tests:
  stage: test
  script:
    - cargo test